### PR TITLE
Redux counter example

### PR DESCRIPTION
**Pull request by alekzonder**
add simple redux-counter example

https://user-images.githubusercontent.com/286330/123984717-105eee00-d9ef-11eb-832c-fd17efa837b6.mp4

### CODE REVIEW

**Comment by ai** [comment]
We deprecated Logux Redux is flavor of Logux Client’ `SyncMap` and Nano Stores 😓

But we don’t have docs yet.

**Comment by alekzonder** [comment]
@ai Hmm... Now you are using  Logux Client’ SyncMap and Nano Stores without Redux at all?

**Comment by ai** [comment]
Yeap. It reduces code boilerplate a lot. Redux is not very useful, too many code around.

**Comment by alekzonder** [comment]
Sounds good, i try to create example with SyncMap, but how do you debug communication?  Redux devtools is very useful

**Comment by ai** [comment]
We have only `log` for Logux actions

**Comment by ai** [comment]
Note, that we do not have CRDT counter for Logux Client yet. It will be better to create ToDo app example.

**Pull request closed without merging**
